brew "fish"
brew "mas"

cask "bettertouchtool"
cask "caffeine"
cask "dropbox"
cask "google-chrome"
cask "iterm2"
cask "java"
cask "licecap"
cask "telegram"
cask "the-unarchiver"
cask "vlc"

# appstore "443987910" "1Password"
# appstore "975937182" "Fantastical 2"